### ISSUE TITLE
Installing with AUR fails

### ISSUE THREAD

**Issue by firstdorsal** [saturneric/GpgFrontend#98] opened 2023-04-19 13:23 UTC
```sh
Updated Git hooks.
Git LFS initialized.
fetch: 179 objects found, done.                                                                                                                                                                           
fetch: Fetching all references...
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                                          
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/saturneric/GpgFrontend.git/info/lfs'
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: gpgfrontend-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
gpgfrontend - exit status 4
```

**Comment by saturneric** [comment] 2023-04-19 14:06
Git LFS of this repo is off now. The AUR maintainer of GpgFrontend may need to update the installation progress.

**Comment by firstdorsal** [comment] 2023-04-19 14:38
I contacted them through the AUR.
Thank you for creating this project!

**Comment by benjamb** [comment] 2023-04-19 15:15
Looks like this has been fixed in the AUR. Any chance of a release that includes this change though? Would be a little nicer to have a clean build without having to cherry-pick the un-lfs commit.

**Comment by Konsonanz** [comment] 2023-04-19 15:16
AUR pkgbuild is [now updated](https://aur.archlinux.org/cgit/aur.git/commit/?h=gpgfrontend&id=5a7a953d6d34b843d159450ca8fe7fd32d09c0ab) for removed lfs by cherry-picking e60faa7569b3188f59f358a8c94a030ed6ba4272 for current v2.1.0 release and should be building again.

**Closed** 2023-05-15 03:17 UTC

**Comment by Ichimikichiki** [comment] 2023-06-08 01:58
This didn't fix it.

**Comment by Konsonanz** [comment] 2023-06-08 10:01
@Ichimikichiki If you judge this as a AUR package issue, then please move the discussion the the [AUR package page](https://aur.archlinux.org/packages/gpgfrontend).

Regardless, for AUR gpgfrontend-2.1.0-2 I just tried the build in a [clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot) and the package was created successfully. Your logs read as if you are still trying to build version 2.1.0-1. Please check if your sources are up to date and if you still run into problems I'm happy to help you on the AUR page discussion section.

**Comment by Ichimikichiki** [comment] 2023-06-08 10:36
Is that right

```bash
makepkg -siCL
==> Making package: gpgfrontend 2.1.0-2 (Thu 08 Jun 2023 08:24:46 PM AEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning gpgfrontend git repo...
Cloning into bare repository '/home/null/.cache/yay/gpgfrontend/gpgfrontend'...
remote: Enumerating objects: 12184, done.
remote: Counting objects: 100% (2946/2946), done.
remote: Compressing objects: 100% (809/809), done.
remote: Total 12184 (delta 2077), reused 2869 (delta 2047), pack-reused 9238
Receiving objects: 100% (12184/12184), 73.79 MiB | 11.97 MiB/s, done.
Resolving deltas: 100% (8544/8544), done.
  -> Cloning json git repo...
Cloning into bare repository '/home/null/.cache/yay/gpgfrontend/json'...
remote: Enumerating objects: 72526, done.
remote: Counting objects: 100% (72526/72526), done.
remote: Compressing objects: 100% (14893/14893), done.
remote: Total 72526 (delta 52933), reused 71155 (delta 51962), pack-reused 0
Receiving objects: 100% (72526/72526), 202.19 MiB | 5.69 MiB/s, done.
Resolving deltas: 100% (52933/52933), done.
  -> Cloning Qt-AES git repo...
Cloning into bare repository '/home/null/.cache/yay/gpgfrontend/Qt-AES'...
remote: Enumerating objects: 570, done.
remote: Counting objects: 100% (570/570), done.
remote: Compressing objects: 100% (236/236), done.
remote: Total 570 (delta 335), reused 561 (delta 330), pack-reused 0
Receiving objects: 100% (570/570), 2.93 MiB | 1.39 MiB/s, done.
Resolving deltas: 100% (335/335), done.
  -> Cloning spdlog git repo...
Cloning into bare repository '/home/null/.cache/yay/gpgfrontend/spdlog'...
remote: Enumerating objects: 30796, done.
remote: Counting objects: 100% (30796/30796), done.
remote: Compressing objects: 100% (7986/7986), done.
remote: Total 30796 (delta 20465), reused 29652 (delta 19727), pack-reused 0
Receiving objects: 100% (30796/30796), 87.74 MiB | 5.31 MiB/s, done.
Resolving deltas: 100% (20465/20465), done.
==> Validating source files with sha256sums...
    gpgfrontend ... Skipped
    json ... Skipped
    Qt-AES ... Skipped
    spdlog ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of gpgfrontend git repo...
Cloning into 'gpgfrontend'...
done.
Downloading resource/lfs/app-image/gpgfrontend/usr/share/applications/gpgfrontend.desktop (155 B)
Error downloading object: resource/lfs/app-image/gpgfrontend/usr/share/applications/gpgfrontend.desktop (370d5e7): Smudge error: Error downloading resource/lfs/app-image/gpgfrontend/usr/share/applications/gpgfrontend.desktop (370d5e78f3c3035e770b1641163fbf945e0a293155a6fecee0808d70ccba59ac): error transferring "370d5e78f3c3035e770b1641163fbf945e0a293155a6fecee0808d70ccba59ac": [0] remote missing object 370d5e78f3c3035e770b1641163fbf945e0a293155a6fecee0808d70ccba59ac

Errors logged to '/home/null/.cache/yay/gpgfrontend/src/gpgfrontend/.git/lfs/logs/20230608T202603.820288861.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: resource/lfs/app-image/gpgfrontend/usr/share/applications/gpgfrontend.desktop: smudge filter lfs failed
==> ERROR: Failure while creating working copy of gpgfrontend git repo
    Aborting...
```
![Screenshot_2023-06-08_20-34-48](https://github.com/saturneric/GpgFrontend/assets/40658431/a94eae46-830d-46e9-a127-60c84ee1ff8b)

**Comment by Konsonanz** [comment] 2023-06-08 11:30
Ah I see, `error: external filter 'git-lfs filter-process' failed` is indicating that during cloning the lfs-step is forced (which does not work with the checked out commit), because the lfs filters are still globally set in the `~/.gitconfig` file. I could reproduce the build fail with those settings.

Unfortunately, that is ultimately a build environment problem:
You can either execute `git lfs uninstall`, `makepkg -siC` and `git lfs install`, to build without forced lfs and restore global .gitconfig afterwards.
But since this is cumbersome, I recommend building with a clean chroot where git lfs is never installed or configured in the first place by using the `extra-x86_64-build` command (it's `buildpkg` for manjaro), at least until a new release gets made where these workarounds are not needed anymore.

**Comment by yochananmarqos** [comment] 2024-06-18 22:03
@saturneric I took over attempting to maintain the AUR package, but it fails to build with Qt6 6.7.1:

```
-- Link GPG Static Library For Unix
[+] Build UI
[+] Build Module
-- Link Application Library For Linux
-- GpgFrontend Install Libraries: mimalloc;spdlog;gpgfrontend_core;gpgfrontend_ui;gpgfrontend_test;gpgfrontend_pinentry;gpgfrontend_module_sdk
CMake Error: File /Qt6CoreConfigureFileTemplate.in does not exist.
CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2277 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:337 (_qt_internal_process_resource)
  /usr/lib/cmake/Qt6LinguistTools/Qt6LinguistToolsMacros.cmake:739 (qt6_add_resources)
  /usr/lib/cmake/Qt6LinguistTools/Qt6LinguistToolsMacros.cmake:689:EVAL:1 (qt6_add_translations)
  CMakeLists.txt:DEFERRED


-- Configuring incomplete, errors occurred!
```

Building succeeds with Qt5 5.15.14, however the application and First Start Wizard open with blank windows and stops responding:

```
❯ GpgFrontend
Loading the "qt_" catalog failed for locale QLocale(English, Latin, United States)
Loading the "qt_" catalog failed for locale QLocale(English, Latin, United States)
Loading the "qtbase_" catalog failed for locale QLocale(English, Latin, United States)
[16:01:51.902] [T:1143783] [default] [  info  ] [GlobalSettingStation.cpp:43] [Impl] -> app path: /usr/bin (+139us)
[16:01:51.902] [T:1143783] [default] [  info  ] [GlobalSettingStation.cpp:44] [Impl] -> app working path: /var/cache/makepkg (+15us)
[16:01:51.902] [T:1143783] [default] [  info  ] [GlobalSettingStation.cpp:59] [Impl] -> app data path: /home/yochanan/.local/share/GpgFrontend (+12us)
[16:01:51.902] [T:1143783] [default] [  info  ] [GlobalSettingStation.cpp:60] [Impl] -> app log path: /home/yochanan/.local/share/GpgFrontend/logs (+3us)
[16:01:51.903] [T:1143783] [default] [  info  ] [init.cpp:155] [InitLocale] -> current system default locale: en_US (+331us)
[16:01:51.903] [T:1143783] [default] [  info  ] [init.cpp:156] [InitLocale] -> locale settings from config:  (+4us)
[16:01:51.903] [T:1143783] [default] [  info  ] [init.cpp:160] [InitLocale] -> application's target locale: en_US (+2us)
Loading the "qt_" catalog failed for locale QLocale(English, Latin, United States)
Loading the "qt_" catalog failed for locale QLocale(English, Latin, United States)
Loading the "qtbase_" catalog failed for locale QLocale(English, Latin, United States)
QIODevice::read (QProcess): device not open
[16:01:51.905] [T:1143783] [ core ] [  info  ] [GpgCoreInit.cpp:297] [InitGpgFrontendCore] -> detected gpgconf path:  (+1775us)
[16:01:51.905] [T:1143783] [ core ] [  info  ] [GpgCoreInit.cpp:298] [InitGpgFrontendCore] -> detected gnupg path:  (+3us)
[16:01:51.906] [T:1143793] [ core ] [warning ] [ModuleInit.cpp:76] [LoadIntegratedMods] -> integrated module directory at path /usr/bin/mods not found, abort... (+1624us)
[16:01:51.922] [T:1143793] [ core ] [  info  ] [GpgCoreInit.cpp:380] [operator()] -> using key database path: /home/yochanan/.gnupg (+15947us)
[16:01:52.390] [T:1143783] [ core ] [warning ] [DataObjectOperator.cpp:112] [GetDataObject] -> data object not found from disk, key: __cache_data_favourite_key_pair (+467874us)
[16:01:52.391] [T:1143783] [ core ] [warning ] [DataObjectOperator.cpp:112] [GetDataObject] -> data object not found from disk, key: __cache_data_editor_unsaved_pages (+1402us)
[16:01:52.391] [T:1143793] [ core ] [warning ] [GlobalModuleContext.cpp:237] [TriggerEvent] -> event APPLICATION_LOADED is not listening by anyone and not registered as well (+66us)
```

**Comment by saturneric** [comment] 2024-06-21 19:17
> @saturneric I took over attempting to maintain the AUR package, but it fails to build with Qt6 6.7.1:
> 
> ```
> -- Link GPG Static Library For Unix
> [+] Build UI
> [+] Build Module
> -- Link Application Library For Linux
> -- GpgFrontend Install Libraries: mimalloc;spdlog;gpgfrontend_core;gpgfrontend_ui;gpgfrontend_test;gpgfrontend_pinentry;gpgfrontend_module_sdk
> CMake Error: File /Qt6CoreConfigureFileTemplate.in does not exist.
> CMake Error at /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:2277 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   /usr/lib/cmake/Qt6Core/Qt6CoreMacros.cmake:337 (_qt_internal_process_resource)
>   /usr/lib/cmake/Qt6LinguistTools/Qt6LinguistToolsMacros.cmake:739 (qt6_add_resources)
>   /usr/lib/cmake/Qt6LinguistTools/Qt6LinguistToolsMacros.cmake:689:EVAL:1 (qt6_add_translations)
>   CMakeLists.txt:DEFERRED
> 
> 
> -- Configuring incomplete, errors occurred!
> ```
> 
> Building succeeds with Qt5 5.15.14, however the application and First Start Wizard open with blank windows and stops responding:
> 
> ```
> ❯ GpgFrontend
> Loading the "qt_" catalog failed for locale QLocale(English, Latin, United States)
> Loading the "qt_" catalog failed for locale QLocale(English, Latin, United States)
> Loading the "qtbase_" catalog failed for locale QLocale(English, Latin, United States)
> [16:01:51.902] [T:1143783] [default] [  info  ] [GlobalSettingStation.cpp:43] [Impl] -> app path: /usr/bin (+139us)
> [16:01:51.902] [T:1143783] [default] [  info  ] [GlobalSettingStation.cpp:44] [Impl] -> app working path: /var/cache/makepkg (+15us)
> [16:01:51.902] [T:1143783] [default] [  info  ] [GlobalSettingStation.cpp:59] [Impl] -> app data path: /home/yochanan/.local/share/GpgFrontend (+12us)
> [16:01:51.902] [T:1143783] [default] [  info  ] [GlobalSettingStation.cpp:60] [Impl] -> app log path: /home/yochanan/.local/share/GpgFrontend/logs (+3us)
> [16:01:51.903] [T:1143783] [default] [  info  ] [init.cpp:155] [InitLocale] -> current system default locale: en_US (+331us)
> [16:01:51.903] [T:1143783] [default] [  info  ] [init.cpp:156] [InitLocale] -> locale settings from config:  (+4us)
> [16:01:51.903] [T:1143783] [default] [  info  ] [init.cpp:160] [InitLocale] -> application's target locale: en_US (+2us)
> Loading the "qt_" catalog failed for locale QLocale(English, Latin, United States)
> Loading the "qt_" catalog failed for locale QLocale(English, Latin, United States)
> Loading the "qtbase_" catalog failed for locale QLocale(English, Latin, United States)
> QIODevice::read (QProcess): device not open
> [16:01:51.905] [T:1143783] [ core ] [  info  ] [GpgCoreInit.cpp:297] [InitGpgFrontendCore] -> detected gpgconf path:  (+1775us)
> [16:01:51.905] [T:1143783] [ core ] [  info  ] [GpgCoreInit.cpp:298] [InitGpgFrontendCore] -> detected gnupg path:  (+3us)
> [16:01:51.906] [T:1143793] [ core ] [warning ] [ModuleInit.cpp:76] [LoadIntegratedMods] -> integrated module directory at path /usr/bin/mods not found, abort... (+1624us)
> [16:01:51.922] [T:1143793] [ core ] [  info  ] [GpgCoreInit.cpp:380] [operator()] -> using key database path: /home/yochanan/.gnupg (+15947us)
> [16:01:52.390] [T:1143783] [ core ] [warning ] [DataObjectOperator.cpp:112] [GetDataObject] -> data object not found from disk, key: __cache_data_favourite_key_pair (+467874us)
> [16:01:52.391] [T:1143783] [ core ] [warning ] [DataObjectOperator.cpp:112] [GetDataObject] -> data object not found from disk, key: __cache_data_editor_unsaved_pages (+1402us)
> [16:01:52.391] [T:1143793] [ core ] [warning ] [GlobalModuleContext.cpp:237] [TriggerEvent] -> event APPLICATION_LOADED is not listening by anyone and not registered as well (+66us)
> ```

@yochananmarqos  I ran into this problem last month on the MSYS2 platform. This appears to be a bug in Qt 6.7.1, and some claim it will be fixed in 6.7.3. See here for details.

https://forum.qt.io/topic/155823/cmake-does-not-work-with-qt-6-7-0/14

**Comment by saturneric** [comment] 2024-07-26 20:55
@yochananmarqos I felt like waiting for a fix for this issue was out of reach, so I tried to work around it on an existing basis. Fortunately, I happened to find the solution. The fix pudding has now hit the main branch and you can release version 2.1.3 on the AUR based on the current main branch code.

For the fix commit, please refer to: cd191d4f876c31697ebf7314b367527ca79f5d3e

**Comment by yochananmarqos** [comment] 2024-07-26 21:35
@saturneric You may want to tag a new version then.

Either way, I was able to build with Qt 6.7.2 and updated the AUR package to the latest commit as 2.1.3+3+g71b9ea8.

**Comment by saturneric** [comment] 2024-07-27 09:04
> @saturneric You may want to tag a new version then.
> 
> Either way, I was able to build with Qt 6.7.2 and updated the AUR package to the latest commit as 2.1.3+3+g71b9ea8.

@yochananmarqos  Have retagged v2.1.3.
