### ISSUE TITLE
Please go back to the old key toolbox

### ISSUE THREAD

**Issue by NearestWater262** [saturneric/GpgFrontend#188] opened 2024-12-19 09:43 UTC
It's so awful to look at. the centered text in each column has this weird padding that makes them much wider than they need to be, plus the centering makes it really difficult to adjust properly, it just feels wrong. the text needs to hug the left of the column like in 2.1.2. also when i restart the app, it doesnt keep my adjustments to the columns so i have to do it every single time and it's frustrating me badly. I use this program a lot and so i will need to stay on old version in order to make this usable for me. please fix this if possible. i understand that the old table did not have adjustable widths columns but this feels even worse.

**Comment by NearestWater262** [comment] 2024-12-19 09:45
the old table just feels much tighter, i can see all the text easily on every start up. on the new table, i start it up and all i see is hidden padded mushed up text it's making me cry

**Comment by saturneric** [comment] 2024-12-20 19:59
I've improved it. You may try the [nightly build](https://github.com/saturneric/GpgFrontend/releases/tag/nightly) at your convenience and see if it's better. If not, fell free to give me further feed back, and I will spend more time working on it later.

Refer: ee3491860f86c65e6af1bc3549e6228c053e34f3

**Comment by NearestWater262** [comment] 2024-12-20 23:17
@saturneric 

it seems you only made the font bigger, nothing has changed from my initial feedback.

also, something is very wrong with this table. whenever I click on the checkboxes in the key toolbox after startup, they are very weird behavior. sometimes they do not check, or it checks a different key than the one i click, and when i favorite certain keys, the correct keys dont show up in the favorite tab. Once I sort the Select tab by Ascending or Descending though, things begin to behave normally it seems.

**Comment by NearestWater262** [comment] 2024-12-20 23:45
By the way, this is what I am talking about. Each column has this awful padding that takes up way too much space. I have put this spacing between these vertical green lines and red lines to show you. Both of these columns in this picture cannot be shrink anymore or else the overflow will be activated. And the text should not be using this centered alignment, it's awful and not data-efficient at all for someone who manages many keys. It's not intuitive, it's just annoying to try and properly shrink/expand such a column.
![image](https://github.com/user-attachments/assets/b2bebcbe-d0f1-4d04-87c6-d27645333f12)


This next image is from your latest stable release, 2.1.6. You can see there is the same issues with all the columns. Also, there is a bit too much horizontal spaces on the rows, which I marked with black lines, to specify what would be more comfortable. But this is a bit more a smaller issue.
![image](https://github.com/user-attachments/assets/45928624-0cfc-4f98-9a48-02db00791cac)


This final one is from your 2.1.2 release. You can see how each column is resting at a comfortable distance between the previous column. No extra dumb padding. No dumb centering. Just proper text resting to the left, as the Holy God intended when He invented the data table. The horizontal spacing between each row is a perfect height. Simply perfect. Also in this table each key that also has a private key is in bold, which seems to be a feature that you removed in the latest release. You should bring that back. Otherwise I cannot simultaneously look at my entire key database while also knowing which are mine.
Of course, the feature to shink/expand the columns is missing, so that is one feature of the new keybox that you should keep
![image](https://github.com/user-attachments/assets/4e8b783d-877e-46d5-94bd-d7daf96ae630)

**Comment by saturneric** [comment] 2024-12-21 02:56
Thank you so much for your detailed feedback! I’ve already identified the root cause of the problem and implemented a fix. The current layout is now just as perfect as it was before. You can try the latest Nightly Build and see if it meets your expectations.

<img width="400" alt="grafik" src="https://github.com/user-attachments/assets/8859ebe1-cbf5-4cd0-8ae5-6e8fcc8f46d5" />

If you're interested, I’d like to share a bit of background on this issue. I actually noticed this problem when it first emerged, but despite spending countless hours reading documentation and experimenting with different solutions, I couldn’t get the table width to automatically adjust to the content. Eventually, I had to put it aside and focus on other pressing tasks.

Over the past few months, I hadn’t received any user reports about this, so I assumed it wasn’t a high-priority issue. But your feedback today gave me the determination to revisit it, and fortunately, after a few hours of effort, I stumbled upon the root cause and managed to fix it.

Your feedback was incredibly valuable because, in my specific usage scenarios, I didn’t fully realize how disruptive this issue could be for other users. If you encounter any further problems or have suggestions for features, please don’t hesitate to share them with me through any channel. With your insights and the Nightly Build cycle, we can quickly address these issues and make the software better and more user-friendly.

**Comment by NearestWater262** [comment] 2024-12-21 07:40
@saturneric Aw, I'm so happy, yes. I am a developer myself so I understand the value of feedback, and yes, of walking away sometimes too :) That's very interesting, and I'm glad I can help you

I will tell you that I am very passionate about GPGFrontend. I find it to be much better and more organized than Kleopatra. Primarily GPGF gives me a much easier notepad experience with ease to open many text doc tabs, with Kleopatra it's a lot more difficult to do this. I am pretty sure you can only have one notepad open. Even when Kleopatra had the key algo supports for key creation that GPGF did not, I only used Kleopatra for key generation, and GPGF for everything else. Also with the key toolbox on the side, meaning dual view of notepad and keys. Kleo doesnt have this. So yes I use GPGF for many many things.

I tried out the nightly image. Yes! it seems the table looks really good now. The only thing I would add would be the functionality to shrink and expand the individual columns. And also that these adjustments are persisting through each startup. 

Something else you could add as well, is a button to revert to preserving this current rigid table style where the columns will always fit around the longest name/email/etc, I think it's still very useful this way.

**Comment by saturneric** [comment] 2024-12-21 18:43
It means a lot to hear that GpgFrontend has become such an essential tool in your workflow, and I’m thrilled that it offers an experience you find smoother and more intuitive than Kleopatra.

Your detailed observations about the notepad functionality, dual-view design, and overall usability are incredibly valuable. It's always encouraging to hear how these features directly improve your day-to-day use.

Regarding your suggestions for the table:
- Resizable Columns: That’s an excellent idea! I’ll look into implementing adjustable column widths with persistence across restarts.
- Rigid Table Style Toggle: I understand the value of preserving the current behavior as an option, and I’ll consider adding a toggle for this as well.

These are both thoughtful improvements that align with the goal of keeping GpgFrontend both flexible and user-friendly. I’ll now close this issue and add your suggestions to my to-do list. If you encounter any further issues or have more ideas, feel free to open a new issue or reach out via email—whichever way you prefer. :)

**Closed by saturneric** 2024-12-21 18:43 UTC
Labels: bug
